# Generated by Django 3.0.8 on 2020-09-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='userlogin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
