# Generated by Django 3.0.8 on 2020-09-27 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to='user.AUser'),
        ),
    ]
