# Generated by Django 3.0.8 on 2020-09-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_contacts_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='reference_currency',
            field=models.CharField(blank=True, default='USD', max_length=255, null=True),
        ),
    ]
