# Generated by Django 3.0.8 on 2020-09-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_wallets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.AUser')),
            ],
        ),
    ]
