# Generated by Django 3.0.8 on 2020-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200928_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionshistory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionshistory',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
