# Generated by Django 3.0.8 on 2020-09-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200928_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionshistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
